### ISSUE TITLE
Review the repository

### ISSUE THREAD

**Issue by RobertvBraam** [antonio-p-silva/super-duper-octo-journey#4]
Hello mister Antonio!

Thank you for the invite. I had some time to take a look at your repository in terms of how does it communicate the intent (😜) of repository, current state of code and possible ideas.

### Intent of the repository
- I like your idea but a question came to mind, "is it going to be valuable enough to take a dependency on or can I build it myself since it's my domain and my types?". Personally I'm someone who's often building these things myself because it will be as stable as you like and it will have the only features I find important (therefore smaller API therefore less overhead). On the other hand there are a lot of developers who like to take dependencies on their repositories for things like Guard classes and so. So I see this as the same category.
- Good to have some examples of what you like to solve, it seems pretty clear to me. I had some ideas on how to make the READ.ME file a bit more clear, but let's talk about it in a PR.

### Repository
It looks all good for new repository, nothing significant to say.

### Possible ideas
- I think the name should be MeaningfulTypes (or something like that), because then it's very clear from the title what it's for. The name now looks a bit like a Chat-GPT generated name.
- Have the test MeaningfulTypes (now private class per test) used as an example, by making them public and referring to them in your READ.ME file. This will not only make sure your Meaningfull types are actually the same and tested everywhere, but also gives the user of the package a good idea on how to use it.

Nice idea and keep up the work, let me know what you think and if you need any help 🦾!

**Comment by antonio-p-silva** [comment]
Working on this now. I've rename the solution. :) I'll work on the readme once all types are done. 
Did the basic ones now: `string`, `guid`, `int`.
Will do:

1. DateTime
2. short
3. long

Wondering if should do `bool`. Make senses to di it, right @RobertvBraam ?
